import type { RawTune } from "./defaultTunes";
import tunesData from "./troupakadaTunes.json";

/**
 * PDF sheets generated by scripts/generate-tune-sheet.mjs (see CLAUDE.md Modification 6), one per tune,
 * named after its descriptionFilename (assets/tuneSheets/<descriptionFilename>.pdf). Imported via
 * import.meta.glob rather than a plain runtime path, for the same reason as maestrationSigns.ts's photos:
 * the production build packs everything into a single HTML file (vite-plugin-singlefile, see vite.config.ts),
 * so a raw "assets/tuneSheets/x.pdf" string would 404 once built.
 */
const tuneSheetUrls = Object.fromEntries(
	Object.entries(import.meta.glob<{ default: string }>("../assets/tuneSheets/*.pdf", { eager: true }))
		.map(([path, module]) => [path.match(/([^/]+)\.pdf$/)![1], module.default])
);

/**
 * Morceaux composés par Troup'akada d'Échirolles, séparés du reste de rawTunes (defaultTunes.ts,
 * dérivé du projet upstream ror-player) pour que les mises à jour de ce fichier — notamment via
 * scripts/import-tunes.mjs ou le bouton "Enregistrer" (voir CLAUDE.md) — n'aient jamais à toucher
 * au gros fichier partagé.
 *
 * Le contenu (patterns, et au besoin descriptionFilename/displayName/sheet/video/speed/exampleSong,
 * cf. le type RawTune) vit dans troupakadaTunes.json ; ce fichier se contente d'y ajouter la
 * catégorie "troupakada" et, si un PDF a été généré pour ce morceau, le champ "sheet" (même lien
 * "Livret des morceaux (PDF)" que pour les morceaux RoR officiels, voir tune-info.vue) — sauf si le
 * JSON définit déjà son propre "sheet" à la main.
 */
export const troupakadaTunes: Record<string, RawTune> = Object.fromEntries(
	Object.entries(tunesData as Record<string, Omit<RawTune, "categories">>).map(([tuneName, tune]) => [
		tuneName,
		{
			...tune,
			categories: [ "troupakada" ],
			sheet: tune.sheet ?? (tune.descriptionFilename ? tuneSheetUrls[tune.descriptionFilename] : undefined)
		} satisfies RawTune
	])
);
